In [1]:
import numpy as np 

In [2]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [3]:
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]


2.32 ms ± 36 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
128 ms ± 2.99 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
data = np.array([[1.5, -0.1, 3], [0, 3, -6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. ,  3. , -6.5]])

In [8]:
data.dtype

dtype('float64')

In [16]:
b = (i for i in range(5))
type(b)

generator

In [17]:
c = (1,2,3) 
type(c)

tuple

In [11]:
np.zeros((1,3,6))

TypeError: unsupported operand type(s) for +: 'range' and 'int'

In [27]:
a = np.full((2,5), fill_value=10)
np.full_like(a, fill_value=13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [58]:
# a = np.empty((3,4), dtype=np.object_)
a = np.empty((3,4), dtype='O')
a

array([[None, None, None, None],
       [None, None, None, None],
       [None, None, None, None]], dtype=object)

In [59]:
a[0,0] = 'dswwwwf'
a[0,1] = [1,2,3,4]
a

array([['dswwwwf', list([1, 2, 3, 4]), None, None],
       [None, None, None, None],
       [None, None, None, None]], dtype=object)

In [35]:
np.string_

b''

In [60]:
arr = np.array([1, 2, 3, 4, 5])
y = arr.astype('f8')

In [64]:
y[0] = 14
y

array([14.,  2.,  3.,  4.,  5.])

In [79]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
numeric_strings.astype(np.float32)
# Calling astype always 
# creates a new array (a copy of the data), even if the new data type is the same as the old data type.

array([ 1.25, -9.6 , 42.  ], dtype=float32)

In [76]:
np.zeros((1,2)).dtype

dtype('float64')

In [84]:
arr = np.array([[1,2,3], [4,5,6]], dtype=float)
arr.dtype

dtype('float64')

In [ ]:
# Indexing 
# array slices are views on the original array, data is not copied 

In [90]:
arr = np.arange(10) 
y = arr[5:8] 
y[:] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [91]:

a = [i for i in range(10)]
b = a[5:8]
b[0] = 99
a  

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [98]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [99]:
old_values = arr3d[0].copy()
arr3d[0] = 12
arr3d
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [101]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [102]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])


In [107]:
a = data[names == "Bob", 1]
id(a)
a[0]= 99


In [108]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [ ]:
# Selecting data from an array by Boolean indexing and assigning the result to a new variable 
# always creates a copy of the data, even if the returned array is unchanged 

In [109]:
data[data < 0] = 0 
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [110]:
arr = np.zeros((8,4))
for i in range(8):
    arr[i] = i

arr 

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [112]:
arr[[3,4,0]] = 12  # view 
arr

array([[12., 12., 12., 12.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [130]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [132]:
a = arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]] 
a[-1] = 99
a

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [99, 99, 99, 99]])

In [135]:
arr[[1,3], [0,2]]

array([ 4, 14])

In [139]:
arr.shape

(8, 4)

In [146]:
# if we want to set values for submatrix with row 2 and 4, column 1 and 3:
xi = np.array([ x in [1,3] for x in range(arr.shape[0])]) 
yi = np.array([ x in [0,2] for x in range(arr.shape[1])])

In [148]:
yi

array([ True, False,  True, False])

In [151]:
xi

array([False,  True, False,  True, False, False, False, False])

In [150]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [167]:
np.array([[99,98], [97,96]]).reshape((-1))

array([99, 98, 97, 96])

In [164]:
arr[xi.reshape((-1, 1)) * yi] = np.array([[99,98], [97,96]]).reshape((-1))

In [169]:
arr

array([[ 0,  1,  2,  3],
       [99,  5, 98,  7],
       [ 8,  9, 10, 11],
       [97, 13, 96, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [182]:
Y = np.arange(16).reshape(4,4)
Y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [175]:
Y[[1,2],[1,3]]

array([ 5, 11])

In [176]:
np.ix_([1,2], [1,3])

(array([[1],
        [2]]),
 array([[1, 3]]))

In [179]:
Y[np.array([[1], [2]]), np.array([[1,3]])]

array([[ 5,  7],
       [ 9, 11]])

In [183]:
# Y[[[1],[2]], [[1,3]]] = 99
Y[[[1],[2]]]

C:\Users\huiyi\AppData\Local\Temp\ipykernel_8140\2384363372.py:2: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  Y[[[1],[2]]]


array([6])

In [187]:
tuple([[1],[2]])


([1], [2])

In [188]:
Y[np.array([[1],[2]])]

array([[[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [190]:
np.array([[1],[2]]).shape

(2, 1)

In [194]:
Y[np.array([[1],[2]])]

array([[[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [195]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [199]:
np.dot(arr.T, arr) 
# .T and swapaxes provide views 
arr.swapaxes(0,1) == arr.T 

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

# Random generator 

In [201]:
samples

1.01492688947694